### PR TITLE
Proposing readme updates

### PR DESCRIPTION
**Pull request by EvanWinget**
Hey @bennyhodl - trying to get this running locally and have started to document the issues I'm running into and steps to resolve them.

An alternative option is to commit your /testconfig/ files to `master` and this PR could be closed out. Can you share your oracledb.dockerfile?

### CODE REVIEW

**Comment by bennyhodl** [comment]
Thanks for catching that I didn't have docs for the oracle. I use the oracle from rust-dlc https://github.com/p2pderivatives/rust-dlc/tree/master/sample#quick-run

I will spend the day writing documentation on running locally. Wish I had it prepared already, but glad I have people trying it out now! 😁

**Comment by bennyhodl** [comment]
Is this file not sufficient for running locally? https://github.com/bennyhodl/dlcdevkit/blob/master/regtest/oracle/oracledb.dockerfile

**Comment by EvanWinget** [comment]
What I ended up doing was:
* Copying the contents of /regtest/ into /testconfig/
* Modifying https://github.com/bennyhodl/dlcdevkit/blob/master/regtest/oracle/oracledb.dockerfile#L4-L5 to:
```
COPY ./certs/db/db.crt /certs/
COPY ./certs/db/db.key /certs/
```
* Modifying https://github.com/bennyhodl/dlcdevkit/blob/master/docker-compose.yaml#L113-L114 to:
```
      context: ./testconfig/oracle
      dockerfile: oracledb.dockerfile
```

I've now got 4 of the 5 containers running but ernest-bitcoin is exiting within 1-2 seconds of initialization with the following error:
2024-09-11 14:55:26 Error: Error reading configuration file: specified config file "/config/bitcoin.conf" could not be opened.

Progress, though! Thanks for leading this project. I've been excited about DLCs for years and am excited to hack on some projects now that you're helping make development more accessible.

**Comment by bennyhodl** [comment]
I updated the documentation and made the development environment easier to start up.

https://github.com/bennyhodl/dlcdevkit/commit/dda8cdc9fc1204a208b96128e82a95a7cbfff312

https://github.com/bennyhodl/dlcdevkit/blob/master/README.md

https://github.com/bennyhodl/dlcdevkit/blob/master/ddk-node/README.md

Let me know if this helps!

**Comment by EvanWinget** [comment]
Nice - this solved it. thanks!

I'm going to create a 2 line PR to fix the copy path in the oracledb.dockerfile and close this one

**Pull request closed without merging**
